### ISSUE TITLE
Live Demo not working

### ISSUE THREAD

**Issue by K3nn3th2** [MirasMustimov/ss-select#20]
Hey guys,

your project looks great.
I'd love to try it, but the live demo is not working.
Is there any additional code necessary?

**Comment by miggiboy** [comment]
> Hey guys,
> 
> your project looks great.
> I'd love to try it, but the live demo is not working.
> Is there any additional code necessary?

Hello, thank you! What exactly doesn’t work? I tried it and it works for me, try to see the demo from another browser or drop me a screenshot

**Comment by K3nn3th2** [comment]
thanks for the reply! 
i use firefox. so tried using brave and it worked without a problem. 
strangely it worked in firefox then, also (which was running in the background).
killing brave and reloading in firefox resulted in an error again. very strange. i cant reproduce this behaviour anymore, either.

Anyway, the error in Firefox:

SyntaxError
Could not fetch dependencies, please try again in a couple seconds: JSON.parse: unexpected character at line 1 column 1 of the JSON data

hope it is of any use
