### ISSUE TITLE
Error importing SsSelect

### ISSUE THREAD

**Issue by K3nn3th2** [MirasMustimov/ss-select#21]
hey, 

I'm having trouble importing SsSelect. I recieve the following error:

Error: 'SsSelect' is not exported by node_modules/ss-select/dist/ss-select.common.js, imported by src/components/blogs/Select.vue?rollup-plugin-vue=script.js
 
The import in the script tag looks like this:

import {
  SsSelect,
  SsSelectToggle,
  SsSelectOption,
  SsSelectSearchInput
} from "ss-select";

what could i be doing wrong?
Edit: It seems to be rollup related.

**Comment by miggiboy** [comment]
@K3nn3th2 please provide some code so i could reproduce your issue. I use webpack and never seen this error before.
