### ISSUE TITLE
Close on select doesn't work on click but works on enter key press

### ISSUE THREAD

**Issue by MirasMustimov** [MirasMustimov/ss-select#7]
Can be related to click outside

**Comment by miggiboy** [comment]
Has to be related to markup! Since I cannot replicate problem with other select. Anyways the reason for  that has to be documented

**Comment by miggiboy** [comment]
Has to be related to markup! Since I cannot replicate problem with other select. Anyways the reason for  that has to be documented

**Comment by miggiboy** [comment]
<ss-select v-model="localValue" :options="resources" :track-by="trackBy" :multiple="true" :max="max" :close-on-select="closeOnSelect" :hide-selected="true" class="leading-normal relative" style="width: 24rem" @open="onOpen" @change="onChange">
        <div slot-scope="{ filteredOptions, selectedOptions, isOpen, pointerIndex, $unselect, $get }">
            <select v-if="input" multiple :name="input.name" class="hidden">
                <option v-for="option in selectedOptions" :value="option[input.valueKey]" selected></option>
            </select>

            <ss-select-toggle class="inline-flex justify-between border-2 rounded-lg cursor-pointer p-1 w-full" :class="[ disabled ? 'pointer-events-none opacity-50' : '' ]">
                <div class="mr-2 flex-1">
                    <div class="flex flex-wrap">
                        <div v-for="selectedOption in selectedOptions" class="flex items-center bg-nova-blue text-gray-100 text-xs rounded py-1 px-2 mb-1 antialiased mr-2">
                            <div class="truncate mr-2" style="max-width: 18rem !important;">{{ get(selectedOption, optionTitle) }}</div>
                            <button type="button" @click.stop="$unselect(selectedOption)">
                                <svg class="svg w-3 h-3 text-gray-400 hover:text-white" viewBox="0 0 20 20"><path d="M10 8.586L2.929 1.515 1.515 2.929 8.586 10l-7.071 7.071 1.414 1.414L10 11.414l7.071 7.071 1.414-1.414L11.414 10l7.071-7.071-1.414-1.414L10 8.586z"/></svg>
                            </button>
                        </div>
                    </div>

                    <div class="flex items-center flex-grow">
                        <ss-select-search-input v-model="query"
                                                class="flex-1 text-base outline-none py-1 px-2"
                                                :placeholder="placeholder"
                                                :clear-on-close="clearSearchOnClose"
                                                @input="onSearch">
                        </ss-select-search-input>
                    </div>
                </div>

                <svg class="flex-none inline-block w-5 h-5 fill-current text-gray-700 mr-1" viewBox="0 0 20 20" style="margin-top: .4rem"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
            </ss-select-toggle>

            <div v-show="isOpen && filteredOptions.length" class="absolute z-10 bg-white w-full border rounded-lg overflow-auto mt-2">
                <div class="overflow-y-auto nova-scrollbar" style="max-height: 16rem">
                    <ss-select-option v-for="(option, index) in filteredOptions"
                                      :value="option"
                                      :key="option.id"
                                      :index="index"
                                      class="text-base px-3 py-1 cursor-pointer"
                                      :class="[ pointerIndex === index ? 'bg-nova-blue text-white' : 'text-gray-800' ]">
                        <div>
                            <div class="font-semibold text-sm">{{ get(option, optionTitle) }}</div>
                            <div v-if="getOptionSubtitle(option)" class="text-sm" :class="[ pointerIndex === index ? 'text-white' : 'text-gray-600' ]">
                                {{ getOptionSubtitle(option) }}
                            </div>
                        </div>
                    </ss-select-option>
                </div>
            </div>
        </div>
    </ss-select>
